name: PHP Composer

on:
  push:
    branches: [ "feature/CI" ]
  pull_request:
    branches: [ "feature/CI" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run test suite
        run: composer run-script test